const fs = require('fs');
fs.readdir('/Users/anmolkhanna/Downloads','utf-8',(err,data)=>{
    console.log(data);
});
// [
//     '.DS_Store',
//         '.localized',
//         '16.jpeg',
//         '1706684431178.jpeg',
//         '1G-to-5G-How-The-Internet-Has-Changed-The-World.jpg',
//         '978-3-642-03869-3_82.pdf',
//         'ASM',
//         'Articles and docs',
//         'Bing_Chats',
//         'Blog Related',
//         'Calendar savings',
//         'Certificated',
//         'CompTIA',
//         'Computer Factory.html',
//         'Computer Factory_files',
//         'Computer Systems A Programmer’s Perspective Third Edition ( PDFDrive ).pdf',
//         'Core_Details_Map',
//         'DBMS',
//         'Drawings',
//         'Employability Next Steps Roadmap.pdf',
//         'Exercise Files from LL',
//         'India’s Feet of Clay_ How Modi’s Supremacy Will Hinder His Country’s Rise.pdf',
//         'KreativStorm',
//         'LL',
//         'Mastering Linux Shell Scripting.pdf',
//         'MicrosoftEdgeDropFiles',
//         'NASM-documentation.pdf',
//         'Obsidian Vault',
//         'Personal',
//         'Programming',
//         'Programming_Savings(2023)',
//         'Programming_Savings_2024',
//         'Programming_Savings_NOV2023',
//         'Resumes',
//         'Scrap_Use',
//         'SwiftSavings',
//         'The Rust Programming Language.pdf',
//         'To push On GIT',
//         'Tools and softwares',
//         'UNI Current',
//         'VM-images',
//         'XAMK',
//         'abs-guide.pdf',
//         'bachmanbooksfour00kin_zsv.pdf',
//         'books on GNU MAKE',
//         'checkingShellType',
//         'codeCrafters',
//         'guessGame',
//         'i8086emu-src-0.9.2',
//         'i8086emu-src-0.9.2.tar.gz',
//         'infoQ',
//         'learn_advanced_modern_cpp_exercises (1).zip',
//         'macOS Terminal',
//         'namit taygi',
//         'rent agreement',
//         'sample.txt'
//     ]
